#!/bin/sh
# shellcheck shell=dash
# Unified dispatcher - routes all commands through the bridge
# Symlinks to this script are created by `bridge --init-wrappers`
#
# How it works:
#   1. Extract command name from how this script was invoked (basename $0)
#   2. Exec bridge with command and args
#   3. Bridge handles: native overrides, sidecar routing, or native fallthrough

CMD=$(basename "$0")
exec bridge "$CMD" "$@"
